import React from "react";
import "./../Nfts/Nfts.css";
import group95 from './../../Assets/Images/Group 96895.png';
import group96 from './../../Assets/Images/Group 96896.png';
import group98 from './../../Assets/Images/Group 96898.png';
import group99 from './../../Assets/Images/Group 96899.png';
import group90 from './../../Assets/Images/Group 96900.png';
import group97 from './../../Assets/Images/Group 96897.png';
import group01 from './../../Assets/Images/Group 96901.png';




const Nfts = () => {
  return (
    <div id="nfts" className="nfts">
      <h1 className="text-center nfts-heading">Popular NFT’s generated by Artists</h1>
      <p className="text-center nfts-text">
        3dotlink's AI integration is a game-changer in the NFT art world. It
        offers a powerful canvas for artists to redefine art creation and
        innovation while preserving cultural art in an entirely new format. With
        this platform, the convergence of human ingenuity and AI technology is
        set to redefine the boundaries of artistic expression and creative
        possibilities, ushering in a digital art renaissance.
      </p>
      <div className="gallery row mt-5">
        <div className="col-4">
            <div className="row g-3">
                <div className="col-12">
                    <img src={group95} alt="" className="img-fluid"/>
                </div>
                <div className="col-12">
                <img src={group96} alt="" className="img-fluid" style={{height:"48.4%", width:"100%"}}/>
                </div>
            </div>
        </div>
        <div className="col-8">
            <div className="row mb-3">
                <div className="col-8">
                    <img src={group98} alt="" className="img-fluid"/>
                </div>
                <div className="col-4">
                    <div className="row mb-3">
                        <div className="col-12">
                            <img src={group99} alt="" className="img-fluid"/>
                        </div>
                    </div>
                    <div className="row">
                        <div className="col-12">
                            <img src={group90} alt="" className="img-fluid"/>
                        </div>
                    </div>
                </div>
            </div>
            <div className="row g-3">
                <div className="col-4">
                <img src={group97} alt="" className="img-fluid"/>

                </div>
                <div className="col-8">
                <img src={group01} alt="" className="img-fluid"/>

                </div>
            </div>
        </div>

      </div>
    </div>
  );
};

export default Nfts;
